name       : haskell-th-compat
version    : 0.1.4
release    : 1
source     :
    - https://hackage.haskell.org/package/th-compat-0.1.4/th-compat-0.1.4.tar.gz : d8f97ac14ab47b6b8a7b0fdb4ff95426322ec56badd01652ac15da4a44d4bab8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Backward- (and forward-)compatible Quote and Code types 
description: |
    This package defines a Language.Haskell.TH.Syntax.Compat module, which backports the Quote and Code types to work across a wide range of template-haskell versions.
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
